[package]
name = "async_zip"
version = "0.0.7"
edition = "2021"
authors = ["Harry [hello@majored.pw]"]
repository = "https://github.com/Majored/rs-async-zip"
description = "An asynchronous ZIP archive reading/writing crate with a heavy focus on streaming support."
readme = "README.md"
license = "MIT"
documentation = "https://docs.rs/async_zip/"
homepage = "https://github.com/Majored/rs-async-zip"
keywords = ["async", "zip", "archive", "tokio"]
categories = ["asynchronous", "compression"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-compression = { version = "0.3.14", features = ["tokio", "deflate", "bzip2", "lzma", "zstd", "xz"]}
async_io_utilities = { git = "https://github.com/Majored/rs-async-io-utilities" }
tokio = { version = "1.19.2", features = ["io-util", "fs"] }
tokio-util = { version = "0.7.3", features = ["io", "compat"] }
chrono = "0.4.19"
crc32fast = "1.3.2"
thiserror = "1.0.31"
reqwest = { version = "0.11", features = ["stream"] }
futures = "0.3"
http-content-range = "0.1.2"

[dev-dependencies]
tokio = { version = "1.19.2", features = ["full"] }
async-compression = { version = "0.3.14", features = ["all"]}
